#!/usr/bin/env bash
# setup-env.sh — Interactive environment setup wizard
# Usage: bash scripts/setup-env.sh --env dev|staging|production

set -euo pipefail

ENV=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env) ENV="$2"; shift 2 ;;
    *) echo "Usage: $0 --env dev|staging|production"; exit 1 ;;
  esac
done

if [[ -z "$ENV" ]]; then
  echo "Which environment are you setting up?"
  echo "  1. dev"
  echo "  2. staging"
  echo "  3. production"
  read -rp "Enter [1]: " choice
  case "$choice" in
    2) ENV="staging" ;;
    3) ENV="production" ;;
    *) ENV="dev" ;;
  esac
fi

case "$ENV" in
  dev) OUTPUT_FILE=".env" ;;
  staging) OUTPUT_FILE=".env.staging" ;;
  production) OUTPUT_FILE=".env.production" ;;
  *) echo "Unknown env: $ENV"; exit 1 ;;
esac

echo ""
echo "Setting up $ENV environment → $OUTPUT_FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Read .env.example to get all variables
if [[ ! -f ".env.example" ]]; then
  echo "ERROR: .env.example not found. Run from workspace root."
  exit 1
fi

declare -A VALUES

generate_secret() {
  openssl rand -base64 32
}

mask_value() {
  local val="$1"
  if [[ ${#val} -le 4 ]]; then
    echo "****"
  else
    echo "${val:0:4}****"
  fi
}

prompt_var() {
  local var_name="$1"
  local description="$2"
  local current_val="${VALUES[$var_name]:-}"
  local is_secret=false

  # Detect secret variables
  if [[ "$var_name" == *"SECRET"* ]] || [[ "$var_name" == *"_KEY"* ]] || [[ "$var_name" == *"_TOKEN"* ]]; then
    is_secret=true
  fi

  echo ""
  if [[ -n "$description" ]]; then
    echo "  # $description"
  fi

  local prompt_text="  $var_name"
  if [[ -n "$current_val" ]]; then
    if $is_secret; then
      prompt_text="$prompt_text [current: $(mask_value "$current_val"), Enter to keep]"
    else
      prompt_text="$prompt_text [current: $current_val, Enter to keep]"
    fi
  elif $is_secret; then
    prompt_text="$prompt_text [Enter value, or type 'generate' for auto-generated secret]"
  fi

  read -rp "$prompt_text: " input

  if [[ -z "$input" && -n "$current_val" ]]; then
    VALUES["$var_name"]="$current_val"
  elif [[ "$input" == "generate" ]]; then
    VALUES["$var_name"]=$(generate_secret)
    echo "  → Generated: $(mask_value "${VALUES[$var_name]}")"
  elif [[ -n "$input" ]]; then
    VALUES["$var_name"]="$input"
  else
    VALUES["$var_name"]=""
  fi
}

# Load existing values if file exists
if [[ -f "$OUTPUT_FILE" ]]; then
  echo "Found existing $OUTPUT_FILE — loading current values."
  while IFS='=' read -r key val; do
    [[ "$key" =~ ^#.*$ ]] && continue
    [[ -z "$key" ]] && continue
    VALUES["$key"]="${val:-}"
  done < "$OUTPUT_FILE"
fi

# Production-specific pre-flight
if [[ "$ENV" == "production" ]]; then
  echo "⚠️  PRODUCTION SETUP — Extra security checks will be applied."
  echo ""
fi

# Parse .env.example and prompt for each uncommented variable
current_comment=""
while IFS= read -r line; do
  if [[ "$line" =~ ^#\ ─── ]]; then
    echo ""
    echo "$line"
    continue
  fi
  if [[ "$line" =~ ^#\ (.+)$ ]]; then
    current_comment="${BASH_REMATCH[1]}"
    continue
  fi
  if [[ "$line" =~ ^([A-Z_]+)=(.*)$ ]]; then
    var_name="${BASH_REMATCH[1]}"
    prompt_var "$var_name" "$current_comment"
    current_comment=""
    continue
  fi
  if [[ "$line" =~ ^#\ ([A-Z_]+)= ]]; then
    # Commented-out optional variable — skip unless already set
    continue
  fi
  current_comment=""
done < ".env.example"

# Validation
echo ""
echo "Validating..."

errors=0
# Check required vars are not empty
for var in NODE_ENV DATABASE_URL BETTER_AUTH_SECRET; do
  if [[ -z "${VALUES[$var]:-}" ]]; then
    echo "  ERROR: $var is required but empty"
    ((errors++)) || true
  fi
done

# Production checks
if [[ "$ENV" == "production" ]]; then
  if echo "${VALUES[DATABASE_URL]:-}" | grep -q "localhost"; then
    echo "  ERROR: DATABASE_URL contains 'localhost' — not allowed in production"
    ((errors++)) || true
  fi
  for secret_var in BETTER_AUTH_SECRET; do
    val="${VALUES[$secret_var]:-}"
    if [[ ${#val} -lt 32 ]]; then
      echo "  ERROR: $secret_var must be at least 32 characters (got ${#val})"
      ((errors++)) || true
    fi
  done
fi

if [[ $errors -gt 0 ]]; then
  echo ""
  echo "Found $errors error(s). Please fix and re-run."
  exit 1
fi

# Write .env file
echo ""
echo "Writing $OUTPUT_FILE..."

{
  echo "# Generated by setup-env.sh — $(date)"
  echo "# Environment: $ENV"
  echo ""
  for key in "${!VALUES[@]}"; do
    echo "${key}=${VALUES[$key]}"
  done
} > "$OUTPUT_FILE"

chmod 600 "$OUTPUT_FILE"
echo "  ✓ Written with chmod 600 (owner read/write only)"

echo ""
echo "Done! $OUTPUT_FILE is ready."

if [[ "$ENV" == "dev" ]]; then
  echo ""
  read -rp "Start Docker infrastructure now? [y/N]: " start_docker
  if [[ "$start_docker" =~ ^[Yy]$ ]]; then
    docker compose up -d
    echo "  ✓ Docker infrastructure started"
  fi
fi
